name: "StanBan"
version: "0.1"
main: "raza.$stanban.PluginMain"
api-version: 1.13
author: "MrRazamataz"
description: "Ban stans from your server with ease"
website: "mrrazamataz.ga"
commands:
permissions:
